import React from "react";
import { useParams } from "react-router-dom";

import { Zap } from "lucide-react";

import moods from "@/constants/moods";
import Track from "@/components/track";
import Container from "@/components/container";
import Breadcrumbs from "@/components/breadcrumbs";

const tracks = [
  { id: 1, title: "I Always Wanna Die (Sometimes)", artist: "The 1975" },
  { id: 2, title: "Fake Happy", artist: "Paramore" },
  { id: 3, title: "COSAS QUE NO TE DIJE", artist: "Saiko" },
  { id: 4, title: "I Like America & America Likes Me", artist: "The 1975" },
  { id: 5, title: "Girls / Girls / Boys", artist: "Panic! At The Disco" },
];

const Mood = () => {
  const { mood: slug } = useParams();
  const mood = moods.filter((mood) => mood.slug === slug)[0];

  if (!mood) {
    return <div></div>;
  }

  return (
    <Container>
      <Breadcrumbs name={mood.name} />
      <div className="mb-2.5 flex flex-row items-center gap-2.5">
        <mood.icon className={mood.color} size={44} />
        <h1 className="scroll-m-20 text-4xl font-semibold tracking-tight lg:text-5xl">
          {mood.name}
        </h1>
      </div>
      <p className="mb-5 text-neutral-400">
        Generated by AI and seeded with Moody's curation of tracks.
      </p>
      <div className="space-y-2">
        {tracks.map((track) => (
          <Track key={track.id} track={track} />
        ))}
      </div>
    </Container>
  );
};

export default Mood;
