import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import { Zap } from "lucide-react";

import playlist from "@/services/playlists";
import moods from "@/constants/moods";
import Track from "@/components/track";
import Container from "@/components/container";
import Breadcrumbs from "@/components/breadcrumbs";

const Mood = () => {
  const { mood: slug } = useParams();
  const mood = moods.filter((mood) => mood.slug === slug)[0];

  if (!mood) {
    return <div></div>;
  }

  const [loading, setLoading] = useState(true);
  const [tracks, setTracks] = useState(null);

  useEffect(() => {
    playlist.get().then((_tracks) => setTracks(_tracks));
  }, []);

  console.log(tracks);

  return (
    <Container>
      <Breadcrumbs name={mood.name} />
      <div className="mb-2.5 flex flex-row items-center gap-2.5">
        <mood.icon className={mood.color} size={44} />
        <h1 className="scroll-m-20 text-4xl font-semibold tracking-tight lg:text-5xl">
          {mood.name}
        </h1>
      </div>
      <p className="mb-5 text-neutral-400">
        Generated by AI and seeded with Moody's curation of tracks.
      </p>
      <div className="space-y-2 pb-8">
        {tracks
          ? tracks.map((track) => <Track key={track.id} track={track} />)
          : null}
      </div>
    </Container>
  );
};

export default Mood;
